### ISSUE TITLE
Numpy version

### ISSUE THREAD

**Issue by MarcDuQuesne** [EnergieID/KNMI-py#9]
When running the test case on a raspberry pi zero, I get the following error:

`ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 124 from C header, got 112 from PyObject`

which may indicate an incompatibility error between the current version of numpy `'1.14.0'` installed on my system and what other libraries expect. 

Maybe consider adding a specific version of numpy to the setup.py?

**Comment by teije01** [comment]
As long as this project can work with multiple versions of numpy, we would not want to restrict the users to use a pinned numpy version as that affects how they can resolve their environment dependencies. I recommend you to install this package in a virtual environment which has numpy installed so that it does not conflict with your system installation.

Closing since outdated.
